---
- name: install packages to use gpg with a smartcard
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg2 #for key crypto
    - rng-tools #true random numbers from HW

- name: download gopass from github
  get_url:
    url: "https://github.com/gopasspw/gopass/releases/download/v{{ gopass_version }}/gopass_{{ gopass_version }}_linux_amd64.deb"
    dest: "/tmp/gopass_{{ gopass_version }}_linux_amd64.deb"
    mode: '0440'

- name: install gopass package
  become: yes
  apt:
    deb: "/tmp/gopass_{{ gopass_version }}_linux_amd64.deb"