---
- name: apt | install python3.
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - python3
      - python3-venv

- name: Copy pip pip-requirements.txt
  copy:
    src: "pip-requirements.txt"
    dest: "/tmp"
    owner: "vagrant"
    group: "vagrant"
    mode: '0664'

- name: pip install pip-requirements.txt
  pip:
    requirements: /tmp/pip-requirements.txt
    executable: pip3

- name: Source venv_devbox in .bashrc
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: 'source "$HOME"/.setenv.sh'
    owner: vagrant
