---
- name: apt | install common packages.
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - unzip
      - git
      - curl
      - ncdu


- name: Copy bash .setenv.sh
  copy:
    src: ".setenv.sh"
    dest: "/home/vagrant"
    owner: "vagrant"
    group: "vagrant"
    mode: '0755'