---
- name: Download aws-cli
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ awscli_version }}.zip"
    dest: "/tmp"
    remote_src: true
    mode: 0755

- name: Check if aws-cli already exists
  stat:
    path: /usr/local/bin/aws
  register: aws_command

- name: Install aws-cli
  ansible.builtin.command:
    cmd: /tmp/aws/install
  when: not aws_command.stat.exists