---

- hosts: all
  become: true
  vars:
    go_tarball: go1.16.3.linux-amd64.tar.gz
    go_tarball_checksum: "sha256:951a3c7c6ce4e56ad883f97d9db74d3d6d80d5fec77455c6ada6c1f7ac4776d2"
    docker__version: "20.10.6"
    docker__channel: ["stable"]
  roles:
    - ansible-docker
    - ansible-infra-tools
    - ansible-go
