---

- hosts: all
  become: true
  vars:
    go_version: 1.16.3
    go_get:
      - name: gopass
        url: github.com/gopasspw/gopass
  roles:
    - fubarhouse.golang
    - ansible-docker
    - ansible-infra-tools
